[versions]
# plugins
kotlin = "2.3.10"
javaVersion = "17"
vanniktech = "0.36.0"
dokka = "2.1.0"
# libs
ktlint = "0.50.0"

# test
junit = "4.13.2"
kover = "0.9.1"
kotest = "5.9.1"
test-report = "1.4"

[libraries]

# test
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotest = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-datatest = { group = "io.kotest", name = "kotest-framework-datatest", version.ref = "kotest" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

# https://github.com/monnage/gradle-test-report
test-report = { id = "com.monnage.test-report", version.ref = "test-report" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }

# https://vanniktech.github.io/gradle-maven-publish-plugin/central/
vanniktech = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }
versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
